type Insumos{
    id_insumos: Int
    descripcion: String
    unidad_medida: String
    id_tipo_almacen: String
    tipo_almacen: String
}

input insumosInput{
    descripcion: String
    unidad_medida: String
    id_tipo_almacen: Int
}

input insumosUpdate{
    id_insumos: Int
    descripcion: String
    unidad_medida: String
    id_tipo_almacen: Int
}