input salidaInput {
   Fecha: String
   id_almacen: Int
   cantidad: Int
   id_sucursal: Int
}

type salidasInfo {
   id_salida: Int
   cantidad: Int
   Fecha: String
   nombreProducto: String
   unidad_de_medida: String
   noSucursal: String
}