input ventasInput {
  key: Float
  productos: [arrayVentas]
}

input arrayVentas {
  id_sucursal: Int
  id_producto: Int
  precio: Float
  cantidad: Int
}

type Ventas {
  id_ventas_productos: Int
  cantidad: Int
  total: Float
  nombre_producto: String 
  nombre_sucursal: String
  empleado: String
}
