type Usuarios{  
 id: Int
 nombre: String
 apellidoP: String
 apellidoM: String
 telefono: String
 email: String
 password: String
 tipo: Int
}

input editarUsuarioInput {
 id: Int
 nombre: String
 apellidoP: String
 apellidoM: String
 telefono: String
 email: String
 password: String
 tipo: Int
}

input usuarioInput {
    nombre: String
    apellidoP: String
    apellidoM: String
    telefono: String
    email: String
    password: String
    cargo: Int
    direccion: String
}

type Token {
  token: String
}