
type Query {
 getUsuarios: [Usuarios]
 getUsuario(id: Int!): Usuarios
 holaMundo: String
 login(correo: String!, contrasenia: String!, key: Float!): Token
 recuperarContranhia(correo: String!, key: Float!): Boolean
}

