
type Query {
 getUsuarios: [Usuarios]
 getUsuario(id: Int!): Usuarios
 holaMundo: String
 login(correo: String!, contrasenia: String!, key: Float!): Token
 recuperarContranhia(correo: String!, key: Float!): Boolean

}

type Mutation {
  createusuario(input: usuarioInput!): Usuarios
  eliminarUsuario(id: Int!): Boolean
  editarUsuario(input: editarUsuarioInput!): Boolean
}

type Usuarios{  
 id: Int
 nombre: String
 apellidoP: String
 apellidoM: String
 telefono: String
 email: String
 password: String
 tipo: Int
}

input editarUsuarioInput {
 id: Int
 nombre: String
 apellidoP: String
 apellidoM: String
 telefono: String
 email: String
 password: String
 tipo: Int
}

input usuarioInput {
    nombre: String
    apellidoP: String
    apellidoM: String
    telefono: String
    email: String
    password: String
    tipo: Int
}

type Token {
  token: String
}