type Query {
  getGasto: [Gasto]
}

type Mutation {
  createGasto(input: gastoInput!): Gasto
  deleteGasto(id_operacion: Int!): Gasto
}

scalar Date

type Gasto {
  id_operacion: Int
  id_producto: Int
  cantidad: Float
  precio: Float
  fecha: Date
  id_usuario: Int
}

input gastoInput {
  id_producto: Int
  cantidad: Float
  precio: Float
  fecha: Date
  id_usuario: Int
}