
type Mutation {
  createGasto(input: gastoInput!): Gasto
}

type Gasto {
  id_operacion: Int
  id_producto: Int
  cantidad: Float
  precio: Float
  fecha: String
  id_usuario: Int
}

input gastoInput {
  id_producto: Int
  cantidad: Float
  precio: Float
  fecha: String
  id_usuario: Int
}