type Mutation {
   createAlmacenProducto(producto: String!, unidadMedida: String!): Boolean
   deleteAlmacenProducto(id_producto: Int!): Boolean
   createAlmacenTipo(nombre: String!): Boolean
   deleteAlmacenTipo(id_tipo_almacen: Int!): Boolean
   editaarTipoAlmacen( idTipoAlmacen: Int!, nombre: String!): Boolean
}