type Query {
  getAlmacen: [Almacen]
  getAlmacenTipo: [AlmacenTipo]
  getAlmacenProducto(id: Int!): Almacen
}

type Mutation {
  createAlmacenProducto(input: almacenInput!): Boolean
  createAlmacenTipo(nombre: String!): Boolean
  deleteAlmacenProducto(id_almacen: Int!): Boolean
  deleteAlmacenTipo(id_tipo_almacen: Int!): Boolean
  updateAlmacenProducto(input: almacenUpdate!): Boolean
  updateAlmacenStock(input: almacenUpdateStock!): Boolean
}

type Almacen {
  id_almacen: Int
  cantidad: Float
  id_insumos: Int
  id_tipo_almacen: Int
  id_sucursal: Int
  nombreTipoAlmacen: String
  nombreSucursal: String
  nombreInsumo: String
}

type AlmacenTipo {
  id_tipo_almacen: Int
  nombre: String
}

input almacenInput {
  cantidad: Float
  id_insumos: Int
  id_tipo_almacen: Int
  id_sucursal: Int
}

input almacenUpdate {
  id_almacen: Int
  cantidad: Float
  id_insumos: Int
  id_tipo_almacen: Int
  id_sucursal: Int
}

input almacenUpdateStock {
  id_almacen: Int
  cantidad: Float
}
