type Query {
  getAlmacen: [Almacen]
  getAlmacenTipo: [AlmacenTipo]
  getAlmacenProducto(id: Int!): Almacen
}

type Mutation {
  createAlmacenProducto(input: almacenInput!): Almacen
  createAlmacenTipo(nombre: String!): Boolean
  deleteAlmacenProducto(id_Producto_Almacen: Int!): Almacen
  deleteAlmacenTipo(id_tipo_almacen: Int!): Boolean
  updateAlmacenProducto(input: almacenUpdate!): Almacen
  updateAlmacenStock(input: almacenUpdateStock!): Almacen
}

type Almacen {
  id_Producto_Almacen: Int
  nombre: String
  categoria: String
  unidad_Medida: String
  status: Int
  stock: Float
}

type AlmacenTipo {
  id_tipo_almacen: Int
  nombre: String
}

input almacenInput {
  nombre: String
  categoria: String
  unidad_Medida: String
  status: Int
  stock: Float
}

input almacenUpdate {
  id_Producto_Almacen: Int
  nombre: String
  categoria: String
  unidad_Medida: String
  status: Int
  stock: Float
}

input almacenUpdateStock {
  id_Producto_Almacen: Int
  stock: Float
}
