input crearEntrada {
    cantidad: Int
    id_tipo_almacen: Int
    id_proveedor: Int
    fechaRegistro: String
    id_almacen: Int
}

type obtenerEntradas {
    id_entrada: Int
    cantidad: Int
    id_tipo_almacen: Int
    id_proveedor: Int
    fechaRegistro: String
    id_almacen: Int
}